_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 4
                - 5
                - 41
                - 53
                - 55
                - 105
            "2":
                - 1
                - 4
                - 5
                - 41
                - 53
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.7
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
bdd_classes:
    value:
        "0": preg
        "1": plas
        "2": pres
        "3": skin
        "4": insu
        "5": mass
        "6": pedi
        "7": age
        "8": classe
entity:
    value: null
framework:
    value: sklearn
job_type:
    value: train
log_preds:
    value: true
processed_data_at:
    value: diabetes_split
project:
    value: mlops-course-assignment
raw_data_at:
    value: diabetes
seed:
    value: 42
